name: Spring Boot CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019, macOS-latest]
        
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        working-directory: project_api
        run: mvn -B package --file pom.xml

  test:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ubuntu-latest, windows-2019, macOS-latest]
        needs: build

        steps: 
        - uses: actions/checkout@v3
        
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
        - name: Run tests
          working-directory: project_api
          run: mvn test
  
        - name: Upload test results (optional)
          uses: actions/upload-artifact@v3
          with:
            name: test-results
            path: target/surefire-reports
